//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YourAccountHasBeenDisabledPleaseContactAdmin.
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA.
        /// </summary>
        public static string AdminType {
            get {
                return ResourceManager.GetString("AdminType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangePasswordPortal.
        /// </summary>
        public static string ChangePasswordPortal {
            get {
                return ResourceManager.GetString("ChangePasswordPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^Y8~JJ.
        /// </summary>
        public static string DefaultSalt {
            get {
                return ResourceManager.GetString("DefaultSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrMsgExceedLicense.
        /// </summary>
        public static string ErrMsgExceedLicense {
            get {
                return ResourceManager.GetString("ErrMsgExceedLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTable.
        /// </summary>
        public static string ErrorTable {
            get {
                return ResourceManager.GetString("ErrorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceed Then Licance Limit.
        /// </summary>
        public static string ExceedThenLicanceLimit {
            get {
                return ResourceManager.GetString("ExceedThenLicanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string fldComment {
            get {
                return ResourceManager.GetString("fldComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromDay.
        /// </summary>
        public static string fldFromDay {
            get {
                return ResourceManager.GetString("fldFromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrLocation.
        /// </summary>
        public static string fldHrLocation {
            get {
                return ResourceManager.GetString("fldHrLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HrLocationCode.
        /// </summary>
        public static string fldHrLocationCode {
            get {
                return ResourceManager.GetString("fldHrLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string fldId {
            get {
                return ResourceManager.GetString("fldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsDisable_Ac_after_UnSuccess_Attempt.
        /// </summary>
        public static string fldIsDisableAcAfterUnSuccessAttempt {
            get {
                return ResourceManager.GetString("fldIsDisableAcAfterUnSuccessAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationCode.
        /// </summary>
        public static string fldLocationCode {
            get {
                return ResourceManager.GetString("fldLocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationDesc.
        /// </summary>
        public static string fldLocationDesc {
            get {
                return ResourceManager.GetString("fldLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuHeadCode.
        /// </summary>
        public static string fldMenuHeadCode {
            get {
                return ResourceManager.GetString("fldMenuHeadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageID.
        /// </summary>
        public static string fldMessageId {
            get {
                return ResourceManager.GetString("fldMessageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageString.
        /// </summary>
        public static string fldMessageString {
            get {
                return ResourceManager.GetString("fldMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOfActiveUsers.
        /// </summary>
        public static string fldNoOfActiveUsers {
            get {
                return ResourceManager.GetString("fldNoOfActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoOfTotalUsers.
        /// </summary>
        public static string fldNoOfTotalUsers {
            get {
                return ResourceManager.GetString("fldNoOfTotalUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentMenuHeadCode.
        /// </summary>
        public static string fldParentMenuHeadCode {
            get {
                return ResourceManager.GetString("fldParentMenuHeadCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password_Min_Len.
        /// </summary>
        public static string fldPasswordMinLen {
            get {
                return ResourceManager.GetString("fldPasswordMinLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegularExpression.
        /// </summary>
        public static string fldRegularExpression {
            get {
                return ResourceManager.GetString("fldRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDay.
        /// </summary>
        public static string fldToDay {
            get {
                return ResourceManager.GetString("fldToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fldUnSuccessfulAtemptAllowed.
        /// </summary>
        public static string fldUnSuccessfulAtemptAllowed {
            get {
                return ResourceManager.GetString("fldUnSuccessfulAtemptAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnSuccessful_Attempt.
        /// </summary>
        public static string fldUnSuccessfulAttempt {
            get {
                return ResourceManager.GetString("fldUnSuccessfulAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgTable.
        /// </summary>
        public static string MsgTable {
            get {
                return ResourceManager.GetString("MsgTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saPwd.
        /// </summary>
        public static string saPwd {
            get {
                return ResourceManager.GetString("saPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;%#@?,:*.
        /// </summary>
        public static string specialChars {
            get {
                return ResourceManager.GetString("specialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        public static string SuperAdminId {
            get {
                return ResourceManager.GetString("SuperAdminId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserIdNotAvailable.
        /// </summary>
        public static string UserIdNotAvailable {
            get {
                return ResourceManager.GetString("UserIdNotAvailable", resourceCulture);
            }
        }
    }
}
